site:
  name: OptimalBody
  site: 'https://ptudja.github.io/optimalbody/'
  base: '/optimalbody/'
#  base: '/' # Use '/' for development locally
  trailingSlash: false

  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: OptimalBody
    template: '%s — OptimalBody'
  description: "\U0001F938\U0001F3FB\u200D\u2640\uFE0F mjesto gdje pokret postaje put prema zdravijem, snažnijem i uravnoteženijem tijelu"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: OptimalBody
    url: 'https://ptudja.github.io/optimalbody/'   # good to include for OG
    images:
      - url: '~/assets/images/optimalbody_1200x630_bg.png'  # Path to your image you want to use for OG
        width: 1200
        height: 630
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

i18n:
  language: hr
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
